# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
        pip3 install pytest pytest-cov pylint setuptools wheel
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: cd dashboard && npm install
    - run: cd dashboard && npm run build
    - run: make package
      if: github.event_name == 'release' && github.event.action == 'created'
    - uses: actions/upload-artifact@v2
      if: github.event_name == 'release' && github.event.action == 'created'
      with:
        name: whitevest
        path: dist/whitevest-johnjones4-*.tar.gz
    - uses: actions/upload-artifact@v2
      if: github.event_name == 'release' && github.event.action == 'created'
      with:
        name: dashboard.dmg
        path: dashboard/dist/*.zip
