name: White Vest Build
on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
        pip3 install pytest pytest-cov pylint setuptools wheel
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: cd dashboard && npm install
    - run: cd dashboard && npm run build
    - run: make package
      if: github.event_name == 'tag'
    - uses: actions/create-release@v1
      if: github.event_name == 'tag'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - uses: actions/upload-release-asset@v1
      if: github.event_name == 'tag'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/whitevest-johnjones4-*.tar.gz
        asset_name: whitevest.zip
        asset_content_type: application/zip
    - uses: actions/upload-release-asset@v1
      if: github.event_name == 'tag'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dashboard/dist/dashboard_*_amd64.snap
        asset_name: dashboard.snap
        asset_content_type: application/snap
